### ISSUE TITLE
Effect of period at end of sentence?

### ISSUE THREAD

**Issue by adarshp** [clulab/eidos#255] opened 2018-04-02 06:50 UTC
With a period at the end of the sentence, one of the causal relations is missed:

<img width="694" alt="screen shot 2018-04-01 at 11 47 57 pm" src="https://user-images.githubusercontent.com/653549/38186295-224a105c-3607-11e8-979b-8e8a84320b5b.png">

But when the period is removed, the third one is picked up:
<img width="692" alt="screen shot 2018-04-01 at 11 48 23 pm" src="https://user-images.githubusercontent.com/653549/38186307-3664710e-3607-11e8-9b9f-d1b526e992ff.png">

Does anyone know why this is?

**Comment by bsharpataz** [comment] 2018-04-02 17:59
addressed.  the issue is syntax. closing for now.

**Closed by bsharpataz** 2018-04-02 17:59 UTC
Labels: help wanted, question
