### ISSUE TITLE
BIO TIME labels should not be in norms

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/eidos#605] opened 2019-06-12 16:11 UTC
The BIO labels generated by the time norm code should be stored in the .entities field of Sentence, not .norms. The latter is used by CoreNLP to store values of entities, e.g., "400" for the entity "four hundred", so it has different semantics, which is needed by Migration events. The TIME BIO labels should be merged with the CoreNLP labels in the .entities field.

**Comment by MihaiSurdeanu** [comment] 2019-06-12 16:12
@BeckySharp: what do you think?

**Comment by MihaiSurdeanu** [comment] 2019-06-12 16:19
Here's an example of this issue:

<img width="793" alt="Screen Shot 2019-06-12 at 9 18 54 AM" src="https://user-images.githubusercontent.com/1179342/59368503-38d5fb80-8cf3-11e9-92ac-000966d54029.png">

**Comment by BeckySharp** [comment] 2019-06-12 16:23
I agree -- until a more elegant solution, we should use Entities, since Norm will be used for things.  To note:
- This likely applies to LOCATION too (@vikas95 @bethard )
- If we use the `entities` field, we can either commandeer it or share it
     - if we commandeer it, we need to be careful about priority
     - if we share, we need to be clever...

**Comment by bethard** [comment] 2019-06-12 16:57
It should be easy to switch from `.norms` to `.entities`. Who uses this info? A quick scan of usages suggests that it's only used in serialization and the webapp (and in the latter, only to display as a table). If I knew who was using it, I could make a better guess as to whether we should commandeer or share.

[Also, I need #604 merged before making any changes to geonorm, but that's failing (like most eidos commits now) because of some issue with ChunkingFeatureFactory?]

**Comment by MihaiSurdeanu** [comment] 2019-06-12 17:04
I do now: we use to understand the actual number of people who migrated. As you know, CoreNLP converts letter numbers, e.g., "four hundred", into the actual number, "400", which is stored in .norms. I use that value to count displaced people.

**Comment by bethard** [comment] 2019-06-12 17:11
I meant, who uses the `B-Time` or `LOC` tags that timenorm and geonorm produce. Not who uses the `.norms` field.

**Comment by BeckySharp** [comment] 2019-06-12 17:36
I think he meant who uses "entities" -- it is temporarily used in the
GazetteerEntityFinder, but as long as that runs first, it should be fine
AND you can overwrite anything that the GazetteerEF added (it is only
needed internally).
this is where we call the GazetteerEF:
https://github.com/clulab/eidos/blob/e766dee9ee64686dcd6484cf5cdeab66c140c4e7/src/main/scala/org/clulab/wm/eidos/EidosSystem.scala#L230

**Comment by bethard** [comment] 2019-06-12 17:43
Another option, if no one is using the `B-Time` and `LOC` tags currently produced by timenorm and geonorm is to not add those at all. Given that `EidosDocument` already stores `TimEx` and `GeoPhraseID` objects separately, maybe there's no need to insert anything into either `.norms` or `.entities`?

**Comment by MihaiSurdeanu** [comment] 2019-06-12 17:53
Yeah, if nobody uses them, then don't add them. I agree.

**Comment by bethard** [comment] 2019-06-12 17:56
Ok. I'll create a pull request that removes both of those entries from `.norms` once someone fixes the issue with ChunkingFeatureFactory and #604 is merged.

**Comment by MihaiSurdeanu** [comment] 2019-06-12 17:57
What ChunkingFeatureFactory issue? @kwalcock: do you know about this?

**Comment by bethard** [comment] 2019-06-12 18:15
All our builds are currently being marked as failing, and they stop right after ChunkingFeatureFactory: https://travis-ci.org/clulab/eidos/builds. Perhaps this is just a configuration issue, and the builds shouldn't be running on Travis at all. But all our commits and pull requests are failing according to to GitHub because of this issue.

**Comment by kwalcock** [comment] 2019-06-12 18:16
This is the first time I've encountered ChunkingFeatureFactory.

Not having the BIO-Time tags sounds good to me because there is an issue with them adequately reflecting the complicated, overlapping time expressions that are found.  See issue #588 and PR #579

**Comment by kwalcock** [comment] 2019-06-12 19:20
Please ignore the Travis output.  If Jenkins passes, that's good.  If Jenkins doesn't even run, then the branch needs some updating.  Travis integration will probably be removed very soon.  Thanks.

**Comment by bethard** [comment] 2019-06-12 19:22
Ok, great. Then I will address this after #604 is merged.

**Comment by BeckySharp** [comment] 2019-06-12 19:50
the labels produced by the neural models are used to make Location and Time mentions, I am not sure if they're used at one point in the creation of the Time and Geonorm objects...

**Comment by bethard** [comment] 2019-06-12 20:05
Could you point out where they are used to make Location and Time mentions? I couldn't find that, but I did find where they are used to attach times and locations to entities:
* org/clulab/wm/eidos/english/grammars/temporalAttachment.yml 
* org/clulab/wm/eidos/english/grammars/geoLocationAttachment.yml
For those cases, is there a reason we use a token-level search, rather than looking for the Location and Time mentions? This is probably my naiveté in how Eidos code and the grammars interact with each other.

**Comment by BeckySharp** [comment] 2019-06-12 21:46
now we are going to be doing just that, but in a newer branch. It wasn't done previously and wasn't an issue until we needed to have mentions for time and location (for the migration events).  but now we do so we will be...
 
now, mentions will be made here: 
https://github.com/clulab/eidos/blob/migration_schema-zupon/src/main/resources/org/clulab/wm/eidos/english/grammars/context.yml

and referenced in 
- org/clulab/wm/eidos/english/grammars/temporalAttachment.yml
- org/clulab/wm/eidos/english/grammars/geoLocationAttachment.yml

(i.e., https://github.com/clulab/eidos/blob/e902f6cd5b1a65036106de88c604428712736344/src/main/resources/org/clulab/wm/eidos/english/grammars/geoLocationAttachment.yml#L10 )

**Comment by BeckySharp** [comment] 2019-06-12 21:47
but we still need a token match to make the mentions, or else they can be made outside of the main extraction process and used to initialize the state.  That's fine too, but then the neural guys would have to make Mentions.

**Comment by bethard** [comment] 2019-06-12 21:59
If you can tell me how to make an appropriate Mention object, I can do it in the appropriate places instead of adding to `.norms`:
https://github.com/clulab/eidos/blob/geonorm-tensorflow/src/main/scala/org/clulab/wm/eidos/document/EidosDocument.scala#L164
https://github.com/clulab/eidos/blob/geonorm-tensorflow/src/main/scala/org/clulab/wm/eidos/document/EidosDocument.scala#L190

**Comment by MihaiSurdeanu** [comment] 2019-06-13 01:13
@BeckySharp ?

**Comment by BeckySharp** [comment] 2019-06-13 03:06
I dont know if this is the way to go... is there a reason you opted to not
use the entities?
If you need to make mentions, I can think about a nice way to do it, but
it’ll take a little thought

**Comment by bethard** [comment] 2019-06-13 03:17
If you're asking why we used `.norms` instead of `.entities`, I'm pretty sure it's because someone at the WM meeting suggested `.norms` to us and not `.entities`. There's certainly no principled reason.

But either of these seem like a hack: we already have the information needed to create an appropriate Mention, but we're decomposing that into token-level tags instead of using it directly. I don't know enough about Odin to understand what's easy or hard in the framework, but at least conceptually it seems odd to start from a mention-like object, and convert it into token-level objects, just so that it can be reconstructed into a mention object.

**Comment by BeckySharp** [comment] 2019-06-13 05:45
Ok, I’ll think about it and try to figure out a clean way to make them, but
using the entities field would prob work just fine

**Comment by BeckySharp** [comment] 2019-06-17 14:52
Hey -- I can't think of a clean way to make them without tagging the sentence twice.  Basically, entities are made with entity finders or in the primary grammars.  The neural model is run on the document at a different time.  IDK if the timenorm (and geonorm) structures _already stored_ in EidosDocument are sufficient to create a mention, **if they are (or could be)**, this is how you'd make a TextBoundMention:
https://github.com/clulab/processors/blob/5c61f03d08bfe7ccc956089301341d1afeca613e/odin/src/main/scala/org/clulab/odin/Mention.scala#L195

The `label` would be "Time" or "Location"
The `foundBy` would be something informative like "TimeNormEF" or something...

and then you'd do the mention-making with a custom EntityFinder (extends [Finder](https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/extraction/Finder.scala)), here are 2 examples:
- [GazetteerEntityFinder](https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/extraction/GazetteerEntityFinder.scala)
- [RuleBasedEntityFinder](https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/extraction/RuleBasedEntityFinder.scala)

alternatively you can just use the `entities` field and make sure you don't get overwritten.

**Comment by bethard** [comment] 2019-06-17 18:09
Yes, we already have all the information needed to create a mention at the time that we're currently injecting the information into `.norms`. So a custom `Finder` that creates `TextBoundMention`s instead sounds like the right thing to do. If I'm reading the interface right, we would just take the current `parseGeoNorm` code, put it in a `Finder`, generate the new `TextBoundMention`s  and add them to the `State` using the `.updated` method. Does that seem about right?

**Comment by BeckySharp** [comment] 2019-06-17 18:34
Almost -- I'm hoping you can do it in 2 steps because currently we run the sentences through the NN as a step in the `annotate` method of EidosSystem ([called here](https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/EidosSystem.scala#L165)).  Then, all the elected entity finders are called [here](https://github.com/clulab/eidos/blob/e766dee9ee64686dcd6484cf5cdeab66c140c4e7/src/main/scala/org/clulab/wm/eidos/EidosSystem.scala#L229), with an api that takes a `Document` (which can be an `EidosDocument` btw) and returns a `Seq[Mention]`.  the "adding to the state" is done in the same step for all entity finders, [here](https://github.com/clulab/eidos/blob/e766dee9ee64686dcd6484cf5cdeab66c140c4e7/src/main/scala/org/clulab/wm/eidos/EidosSystem.scala#L231).  

So, if you can use the extra content of the already-annotated `EidosDocument` to make the mentions, we won't have to change the APIs (if that makes sense), unless I'm missing something obvious and easier.  You'll just have to make an Entity Finder with a `fromConfig` method (as they get created [here](https://github.com/clulab/eidos/blob/master/src/main/scala/org/clulab/wm/eidos/extraction/Finder.scala#L16)).

**Comment by bethard** [comment] 2019-06-17 18:37
Thanks for the pointers. I'll give this a try once the geonorm-tensorflow branch is merged.

**Comment by BeckySharp** [comment] 2019-06-17 18:47
👍 let me know if you need anything!

**Comment by kwalcock** [comment] 2019-06-17 18:55
I'm getting to that merge very soon.

**Comment by bethard** [comment] 2019-06-17 18:56
No rush. I'm working on several other things too.

**Comment by bethard** [comment] 2019-06-20 21:00
I'm working on this now. Where is the [piece of grammar that links locations to entities](https://github.com/clulab/eidos/blob/master/src/main/resources/org/clulab/wm/eidos/english/grammars/geoLocationAttachment.yml) tested?

I've removed the `"LOC"` entries from `.norms` in my current work-in-progress, but this doesn't cause [TestDoc3 Paragraph 4](https://github.com/clulab/eidos/blob/master/src/test/scala/org/clulab/wm/eidos/text/english/eval6/TestDoc3.scala#L111) to fail like I thought it would.

**Comment by BeckySharp** [comment] 2019-06-20 21:20
indirectly, where you think, e.g., places like [here](https://github.com/clulab/eidos/blob/master/src/test/scala/org/clulab/wm/eidos/text/english/eval6/TestDoc3.scala#L132)

If you are already adding mentions with an entity finder then I would expect anything to fail, perhaps to duplicate (or maybe not)

**Comment by bethard** [comment] 2019-06-20 21:24
Thanks. I managed to get the test to fail as I believe it should with no `"LOC"` in `.norms`. What do I need to replace `[norm="LOC"] [norm="LOC"]*` with if I want to match a `"Location"` `TextBoundMention` instead?

**Comment by kwalcock** [comment] 2019-06-20 21:59
Thanks.  I was looking to see how it could still pass without a LOC, but it sounds like there may have been a LOC still there.

**Comment by bethard** [comment] 2019-06-20 22:19
I take back my "managed to get the test to fail" comment. TestDoc3 Paragraph 4 is still passing on my machine despite deleting the `.norms` stuff and not having made any changes to the grammar. If @BeckySharp or @kwalcock could take a look at that commit on the geonorm-finder branch and help me understand why that test isn't failing, I'd be grateful.

**Comment by kwalcock** [comment] 2019-06-20 22:22
Yes, and thanks for the branch.  It may well be that something was overlooked.

**Comment by BeckySharp** [comment] 2019-06-20 22:52
> Thanks. I managed to get the test to fail as I believe it should with no `"LOC"` in `.norms`. What do I need to replace `[norm="LOC"] [norm="LOC"]*` with if I want to match a `"Location"` `TextBoundMention` instead?

If you're replacing it in a `trigger` field -- I think you'd replace `trigger = ....` with `trigger: Location` 

If it's in a surface pattern, you'd replace it with `@Location`

Let know if that doesn't work

**Comment by kwalcock** [comment] 2019-06-20 22:57
Just now it is looking like there is an attachment on the mention foundBy = "org.clulab.wm.eidos.context.GeoNormFinder++gazetteer++simple-np++quantification2++Increase_adjective_rule_1"

**Comment by kwalcock** [comment] 2019-06-20 23:20
And useTimeNorm and useGeoNorm are both on, despite one having been removed from eidos.conf.  The one comes from
```
def useGeoNorm = ieSystem.loadableAttributes.entityFinders.collect{ case f: GeoNormFinder => f }.nonEmpty
```
So is the question, why is GeoNormFinder finding what is tested for?  I'm not sure about that.

**Comment by kwalcock** [comment] 2019-06-20 23:55
It looks like useGeoNorm is in both GraphTester and in TestUtils as well as EidosSystem and some configuration files.  The value might not have the expected value.

**Comment by bethard** [comment] 2019-06-21 16:00
I did check that by printing it out in the test file, and useGeoNorm was true (which it would need to be for the tests to fall). Is it printing false for you?

**Comment by kwalcock** [comment] 2019-06-21 16:21
My theory is that it might be passing for you because useGeoNorm is off and it is skipping the test.  Are you observing that variable in NodeSpec.matchAttachments (GraphSpec.scala line 271)?

**Comment by bethard** [comment] 2019-06-21 17:47
I was printing out `tester.useGeoNorm` here:
https://github.com/clulab/eidos/blob/master/src/test/scala/org/clulab/wm/eidos/text/english/eval6/TestDoc3.scala#L129

**Comment by kwalcock** [comment] 2019-06-21 18:48
The way I got it to fail was to turn off the geonorm entityFinder in englishTest.conf: `entityFinders = ["gazetteer", "rulebased"]` completely.  This will unfortunately also turn off the tests for geonorm.  Then I hard-wired useGeoNorm to true in EidosSystem.scala, GraphTeste.scala, and TestUtils.scala where we've got some duplicated code.  In your branch it looked like the geonorm entityFinder was active and the tests for geonorm were being performed and passing.

**Comment by bethard** [comment] 2019-06-21 19:03
My understanding is that the tests should also fail when the GeoNormFinder is included and useGeoNorm is true, because my branch has not corrected the grammar at all. So I'm looking to make it fail not when the GeoNormFinder is removed, but when the GeoNormFinder is included.

**Comment by kwalcock** [comment] 2019-06-21 19:15
OK.  The `GeoLoc("Greater Equatoria")` is being found, though.  If it eventually doesn't get found, either because of uncorrected grammar or disabling the GeoNormFinder, then then test does seem to fail.  I had to use the latter method.  That doesn't help you much, though.  The test is not somehow stuck on passing only.

**Comment by BeckySharp** [comment] 2019-06-21 19:33
Does it pass if you comment out this rule:
https://github.com/clulab/eidos/blob/8c6354d612ed21a7c48f6f57bb19ffb4d821b701/src/main/resources/org/clulab/wm/eidos/english/grammars/geoLocationAttachment.yml#L5

?

**Comment by bethard** [comment] 2019-06-21 20:47
I commented out `import: org/clulab/wm/eidos/english/grammars/geoLocationAttachment.yml` etc. in `master.yml`. The tests still pass. Is there anywhere else in the code that could be attaching `Location` mentions to `Entity` mentions?

**Comment by BeckySharp** [comment] 2019-06-21 20:49
if you look at the `foundBy` field of the Location mentions themselves,
what does it say?

**Comment by bethard** [comment] 2019-06-21 20:56
As per [Keith's comment](https://github.com/clulab/eidos/issues/605#issuecomment-504228290), you can see the new Finder is filling `foundBy` with `org.clulab.wm.eidos.context.GeoNormFinder`. But the issue is not finding the `Location` mentions; I'm creating those, so I know how they're appearing. What I don't know is how they're getting attached to the causal events.

**Comment by bethard** [comment] 2019-06-24 17:09
@BeckySharp and I met and discussed the issue. Because all of our tests are for cases where the Location is within the text of the (expanded) entities, and because Eidos has special code to automatically copy attachments from other mentions within an entity mention, no additional grammar rules are needed to attach the locations to the entities. That is, once we change from modifying `.norms` to creating actual `Location` mentions with a `Finder`, there is no need for any grammar rules.

(For now at least; if we want to attach `Location`s that are not within the entities, we will need to add grammar rules for that. But I think we should not add any rules until we see some actual language where `Location`s are not within the entities but still need to be attached.)

**Comment by bethard** [comment] 2019-06-28 22:01
Reopening this issue, since the TIME labels are still in norms. I've started work on converting timenorm to a `Finder` like I did for geonorm, and I've linked the branch with those changes to this issue.

I don't know how to update the rules to deal with mentions instead of norms. For example, here's a failure that I'd like to correct, where the `Time` is being found, but not attached, but even after looking through the Odin manual, I have no idea how to fix the rule in [temporalAttachment.yml](https://github.com/clulab/eidos/blob/master/src/main/resources/org/clulab/wm/eidos/english/grammars/temporalAttachment.yml).
```
[info] TestDoc3 Paragraph 9
[info] - should have correct edges 1
[info] - should have correct edges 2
[info] - should have correct edges 3
[info] - should have correct edges 4
[info] - should have correct edges 5 *** FAILED ***
[info]   List("Could not find EdgeSpec [Rainfall|+QUANT(moderate to heavy)+TIME(coming weeks)]->(Causal)->[rainfall deficits|+DEC(deficits)+DEC(erase)]", "Mentions:
[info]   0: Rainfall Quantification(moderate to heavy,None)
...
[info]   12: coming weeks Time(coming weeks)
```

Also, I see some places where the test is failing, but the test output makes it seem like everything is attached correctly. What am I missing?
```
[info] TestDoc2:
[info] TestDoc2 Paragraph 1
[info] TestDoc2 Paragraph 2
[info] - should have correct singleton node 3
[info] - should have correct singleton node 4 *** FAILED ***
[info]   List("Could not find NodeSpec [level of food insecurity this year|+QUANT(unprecedented)+TIME(this year)]", "Mentions:
...
[info]   7: this year Time(this year)
[info]   8: level of food insecurity this year Quantification(unprecedented,None), Time(this year)
```

**Comment by kwalcock** [comment] 2019-06-28 22:37
I'll check out the second one.

**Comment by kwalcock** [comment] 2019-07-01 16:54
It looks to me like the problem is that useTimeNorm is false.  In EidosSystem I think it needs
```
  def useTimeNorm: Boolean = loadableAttributes.entityFinders.collectFirst{ case f: TimeNormFinder => f }.isDefined
```

When we recently started turning these on and off we didn't not make it flexible enough to do both.  If it is off, the TimEx("this year") should be removed.  I should program it so that it is automatically ignored.

**Comment by bethard** [comment] 2019-07-01 18:05
Of course! I forgot to delete `LoadableAttributes.timenorm`. Yes, deleting that and changing `useTimeNorm` as you indicated fixes the tests that do not need grammar-based attachments.

@BeckySharp: Any examples you can point me at for how to write a grammar rule that connects a `Time` Eidos Mention to an `Entity` Eidos Mention in whatever way it needs to be connected?

**Closed** 2019-07-12 16:35 UTC
