### ISSUE TITLE
jnius.JavaException 

### ISSUE THREAD

**Issue by remondulos** [clulab/eidos#552] opened 2019-01-23 10:27 UTC
```
from indra.sources import eidos

ep = eidos.process_text("Water trucking has decreased due to the cost of fuel.")
print(ep.statements)
```

When running the code above, I receive the following: jnius.JavaException: Invalid instance of 'org/clulab/wm/eidos/EidosSystem' passed for a 'org/clulab/wm/eidos/groundings/AdjectiveGrounder'. 

I have added the eidos jar file to CLASSPATH and to /indra/indra/resources/default_config.ini and as well to /root/.config/indra/config.ini

Am I missing something here?

> 10:13:34.913 [main] INFO  org.clulab.wm.eidos.EidosSystem$ - Loading processor...
> 10:13:34.917 [main] INFO  org.clulab.wm.eidos.EidosSystem$ - Loading W2V...
> 10:13:34.957 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/filtering/stops.txt
> 10:13:34.976 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/filtering/transparent.txt
> 10:13:34.980 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/confidence/hedging.txt
> 10:13:34.985 [main] INFO  org.clulab.wm.eidos.EidosSystem$ - Loading loadableAttributes...
> 10:13:34.986 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/grammars/master.yml
> 10:13:34.990 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/grammars/taxonomy.yml
> 10:13:35.227 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
> 10:13:35.533 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 20
> 10:13:36.551 [main] INFO  org.nd4j.nativeblas.Nd4jBlas - Number of threads used for BLAS: 20
> 10:13:36.556 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Linux]
> 10:13:36.556 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [80]; Memory: [7.1GB];
> 10:13:36.556 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [OPENBLAS]
> 10:13:39.877 [main] INFO  o.d.nn.graph.ComputationGraph - Starting ComputationGraph with WorkspaceModes set to [training: ENABLED; inference: ENABLED], cacheMode set to [NONE]
> 10:13:39.931 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/grammars/entities/grammar/entities.yml
> 10:13:40.753 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/grammars/avoidLocal.yml
> 10:13:40.788 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/quantifierKB/domain_parameters.kb
> 10:13:40.790 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/quantifierKB/gradable_adj_fullmodel.kb
> 10:13:41.256 [main] INFO  org.clulab.sequences.LexiconNER - Beginning to load the KBs for the rule-based bio NER...
> 10:13:41.263 [main] INFO  org.clulab.sequences.LexiconNER - Loaded matcher for label Quantifier. This matcher contains 219 unique strings; the size of the first layer is 219.
> 10:13:41.268 [main] INFO  org.clulab.sequences.LexiconNER - Loaded matcher for label Property. This matcher contains 189 unique strings; the size of the first layer is 164.
> 10:13:41.268 [main] INFO  org.clulab.sequences.LexiconNER - KB loading completed.
> 10:13:41.384 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
> 10:13:41.833 [main] INFO  e.s.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [0.4 sec].
> 10:13:41.848 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
> 10:13:41.892 [main] INFO  e.s.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
> 10:13:41.917 [main] INFO  e.s.nlp.sequences.SeqClassifierFlags - maxAdditionalKnownLCWords=0
> 10:13:42.697 [main] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [0.8 sec].
> 10:13:43.035 [main] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [0.3 sec].
> 10:13:43.399 [main] INFO  e.s.n.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [0.4 sec].
> 10:13:43.401 [main] INFO  e.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
> 10:13:43.754 [main] DEBUG e.s.n.l.t.CoreMapExpressionExtractor - Ignoring inactive rule: null
> 10:13:43.754 [main] DEBUG e.s.n.l.t.CoreMapExpressionExtractor - Ignoring inactive rule: temporal-composite-8:ranges
> 10:13:43.841 [main] INFO  e.s.n.parser.nndep.DependencyParser - Loading depparse model file: edu/stanford/nlp/models/parser/nndep/english_UD.gz ...
> 10:13:52.668 [main] INFO  e.s.nlp.parser.nndep.Classifier - PreComputed 99996, Elapsed Time: 7.885 (s)
> 10:13:52.669 [main] INFO  e.s.n.parser.nndep.DependencyParser - Initializing dependency parser ... done [8.8 sec].
> 10:13:52.745 [main] INFO  e.s.nlp.sequences.SeqClassifierFlags - macro=true
> 10:13:52.745 [main] INFO  e.s.nlp.sequences.SeqClassifierFlags - featureCountThresh=10
> 10:13:52.745 [main] INFO  e.s.nlp.sequences.SeqClassifierFlags - featureFactory=org.clulab.processors.corenlp.chunker.ChunkingFeatureFactory
> 10:13:53.473 [main] INFO  org.clulab.wm.eidos.utils.Sourcer$ - Sourcing resource file:/eidos/target/scala-2.12/eidos-assembly-0.2.2-SNAPSHOT.jar!/org/clulab/wm/eidos/english/context/word2idx_file.txt
> Traceback (most recent call last):
>   File "workdir/eidos.py", line 3, in <module>
>     ep = eidos.process_text("Water trucking has decreased due to the cost of fuel.")
>   File "/opt/conda/lib/python3.6/site-packages/indra/sources/eidos/api.py", line 54, in process_text
>     json_dict = eidos_reader.process_text(text, out_format)
>   File "/opt/conda/lib/python3.6/site-packages/indra/sources/eidos/reader.py", line 94, in process_text
>     corpus = jc(ml, self.eidos_reader)
>   File "jnius/jnius_export_class.pxi", line 253, in jnius.JavaClass.__init__
>   File "jnius/jnius_export_class.pxi", line 315, in jnius.JavaClass.call_constructor
>   File "jnius/jnius_conversion.pxi", line 63, in jnius.populate_args
>   File "jnius/jnius_utils.pxi", line 207, in jnius.check_assignable_from
> jnius.JavaException: Invalid instance of 'org/clulab/wm/eidos/EidosSystem' passed for a 'org/clulab/wm/eidos/groundings/AdjectiveGrounder'

**Comment by kwalcock** [comment] 2019-01-23 14:49
Is this with the master branch version?  Eidos doesn't have a process_text function there.  Some related things have changed, though.  EidosSystem is no longer itself an AdjectiveGrounder.  We might have some stale documentation somewhere.  Can you copy a little more of the Python code?  I don't see anything in the stack trace that looks like a problem.  What does eidos.process_text call?  Thanks.

**Comment by bgyori** [comment] 2019-01-23 15:07
A change in Eidos a few days ago broke the integration with INDRA which was fixed in this PR https://github.com/sorgerlab/indra/pull/782. If you update INDRA to the latest version, it should work again.

**Comment by kwalcock** [comment] 2019-01-23 15:51
Thanks, Ben.  I updated the example in README.md.  It would be nice to get rid of that second argument completely.  I'll look into it and remember to notify you of any change this time.

**Comment by kwalcock** [comment] 2019-01-23 16:24
Is AdjectiveGrounding, i.e., that part of the jsonld output, normally used?  We could have a constructor without the second argument to simplify life for those who aren't using it.

**Comment by bsharpataz** [comment] 2019-01-23 16:49
Yeah, that sounds good -- I would like to refactor that whole thing, but
that sounds good in the meantime!
thanks!

**Comment by kwalcock** [comment] 2019-01-23 17:24
@bsharpataz If it's OK for things other than EidosSystem to handle their own configuration a la fromConfig, then the Corpus or Serializer could handle the adjective grounder internally and not rely on something else to pass it in, either handing over the EidosSystem version of it or some other one.  It looks like it is not used elsewhere.  The quantifierKBPath might then be better placed in its own "stanza" in eidos.config.  Is there a good name for it?  You have this marked as a TODO, with much foresight, and maybe now is a good time.

**Comment by bsharpataz** [comment] 2019-01-23 21:07
Now indeed seems like a fine time, and I think more "stanzas" would be fine
(esp since they can hide in the reference.conf if we seldom mess with
them), but I didn't follow the full question you asked so I can't
completely answer the subquestions (sorry!)

**Comment by kwalcock** [comment] 2019-01-24 04:13
My idea won't work as intended.  EidosSystem still needs first crack at the Config passed in.  It has to find a "stanza" and pass it on to some component via fromConfig.  The problem is that EidosSystem is not involved in creation of a JLDCorpus or its serialization, so that it doesn't have a ready way to convey the config information to either the JLDCorpus or JLDSerializer.  This is why the client is passing on the information now in ExtractFromDirectory and elsewhere:
```scala
      val corpus = new JLDCorpus(annotatedDocuments, reader.loadableAttributes.adjectiveGrounder)
      val mentionsJSONLD = corpus.serialize()
````
It seems like the alternative would need to be something like
```scala
      val corpus = new JLDCorpus(annotatedDocuments)
      val mentionsJSONLD = reader.serialize(corpus)
```
or
```scala
      val corpus = reader.encorpusate(annotatedDocument)
      val mentionsJSONLD = corpus.serialize()
```
It might be handy if reader.serialize() could be made to include the default adjective grounder while corpus.serialize() could skip the grounding.

**Comment by kwalcock** [comment] 2019-01-25 15:58
@bgyori, are you aware of anything there that is using the adjective grounding in the output?  These are the intercept, mu, and sigma values on things called modifiers in the JLD output.  We have an update in the pipeline that makes the adjective grounder optional so that your code related to sorgerlab/indra#782 could be changed to
```python
            # ag = self.eidos_reader.loadableAttributes().adjectiveGrounder()
            # We now create a JSON-LD corpus
            jc = autoclass(eidos_package + '.serialization.json.JLDCorpus')
            corpus = jc(ml) # , ag)
```
If you do need that grounding, it would be done slighly differently after the change makes it to master, and I can show the example Scala code.

**Comment by bgyori** [comment] 2019-01-25 19:49
My opinion on adjective quantification is that it is easier to do downstream of reading i.e. the numbers don't need to be baked into the reading result. I'll adapt the code in INDRA once the change is merged here. Thanks!

**Closed** 2019-02-28 20:21 UTC
